{% set ident = "ItemModels" %}
{% set name = "k" ~ ident|lower %}
{% set version = "5.71.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: 68205f09d63a916f236e2b3b729c0055377d852de48f7cf29fa7174ca97b84e7

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('libudev') }}  # [linux]
    - {{ cdt('libudev-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5{{ ident }}.so

about:
  home: https://api.kde.org/frameworks/{{ name }}/html/index.html
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Network transparent access to files and data
  description: |
    {{ ident }} part of the KF5 framework
  dev_url: https://cgit.kde.org/{{ name }}.git/tree

extra:
  recipe-maintainers:
    - zklaus
