{% set ident = "ItemModels" %}
{% set name = "k" ~ ident|lower %}
{% set version = "5.110.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: 123a7f4511f74f4a20aebf4d7194bfe46c71bdf3d3c3cc4864d71262c6a8fe19

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('libudev') }}  # [linux]
    - {{ cdt('libudev-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt-main

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5{{ ident }}.so

about:
  home: https://api.kde.org/frameworks/{{ name }}/html/index.html
  license: LGPL-2.1-only
  license_family: GPL
  license_file:
    - LICENSES/CC0-1.0.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
  summary: Network transparent access to files and data
  description: |
    {{ ident }} part of the KF5 framework
  dev_url: https://invent.kde.org/frameworks/{{ name }}

extra:
  recipe-maintainers:
    - zklaus
